---
- hosts: linux
  vars:
   ansible_become: yes
   ansible_become_method: su
   ansible_become_user: root
   ansible_become_pass: "{{ root_password }}{{ end_ip }}"

  vars_prompt:
    - name: "password"
      prompt: "Enter Password"
      private: yes
      confirm: yes

    - name: "root_password"
      prompt: "Enter Root Password"
      private: yes
      confirm: yes

    - name: "new_password"
      prompt: "Enter New Password"
      private: yes
      confirm: yes

  roles:
    - linux
