---
- name: Change password of existing test1
  user: 
    name: test1 
    update_password: always 
    password: "{{ ansible_ssh_new_pass | password_hash('sha512')}}"

- name: Change password of existing test2
  user: 
    name: test2 
    update_password: always 
    password: "{{ ansible_ssh_new_pass | password_hash('sha512')}}"
