---
- name: Linux Client SSH Check 
  hosts: linux
  gather_facts: no

  vars_prompt:
    - name: "password"
      prompt: "Enter Password"
      private: yes
      confirm: yes

  tasks:
  - name: SSH Check
    ping:
